description=Stages the bot cert for the Collab Tools Proxy.
installScript=bot-cert.sh
itarRestricted=false
documentationFile=README.md
assetType=SOFTWARE
dataImpactLevel=NONE
name=Collab Tools Proxy - Bot Cert - Template
softwareAssetType=APPLICATION
licenseFile=LICENSE.md
assetRealmType=USER_REALM
